### ISSUE TITLE
Add-on Doesn't show up after installing + additional errors

### ISSUE THREAD

**Issue by Retrax57** [wisaac407/blender-edge-sets#1]
The add-on after installation doesnt show up anywhere. I took the liberty to execute the script file from the text editor and then it shows up perfectly, but this error shows up in the info panel:-
![edgesetsbug](https://user-images.githubusercontent.com/30665831/34910848-d168f0ec-f900-11e7-880a-8d3b07de92ba.png)
Hope you fix it, this add-on has a lot of potential and already solves half of all my problems as a hard surface modeller.

**Comment by wisaac407** [comment]
Thanks for your interest in this project!

Are you installing the zip of the entire project? Or just the one .py file?

**Comment by Retrax57** [comment]
I tried both ways, at first I only used the script file, it didn't work or show up so I put in a folder and renamed it to _init_ and executed it using the add-on development add-on.

**Comment by wisaac407** [comment]
Is there any output in the console when you try to install the addon?

**Comment by Retrax57** [comment]
Fixed the problem. I originally unzipped the file and copied the py file manually to the blender add-on root folder, now I removed the files from the folder and re-installed using the installer directly and then it worked. Strange, I have been manually copying my add-ons and they all have worked fine in the past, this was unexpected.

**Comment by wisaac407** [comment]
Hmm, that's weird. I'm glad you got it to work.

I'd love to hear how it works for you!
